# Version of Docker Compose
version: "3"

services: 
  app:
    build:
      context: .
    ports: 
      - "8000:8000" # Map from port 8000 on host to 8000 on image
    volumes:          # Maps volume of local machine to Docker Container in real-time
      - ./app:/app  # Maps the app directory in local machine to the app directory in docker container
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on: 
      - db 

  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
